FROM docker-registry.wikimedia.org/wikimedia-jessie:latest

RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
    apt-get -y --no-install-recommends install python3 python3-dev python3-pip \
            python3-setuptools git \
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && pip3 install --upgrade pip \
    && mkdir /wheels && pip3 install wheel

COPY run.sh /bin/run.sh

VOLUME ["/wheels", "/deploy"]

CMD ["/bin/run.sh"]
